apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-authentication
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-authentication
    spec:
      containers:
      - name: customer-authentication
        image: reactivesw/customer-authentication:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: server_port
          value: "80"
        - name: spring_datasource_url
          value: jdbc:postgresql://pg-data/customer_authentication
        - name: spring_cloud_config_uri
          value: http://reactivesw-config
        - name: umasuo_test_uri
          value: http://customer-info/test