apiVersion: v1
kind: Service
metadata:
  name: customer-authentication
  labels:
    name: customer-authentication
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    app: customer-authentication
