server:
  port: 8083

spring:
  datasource:
#    url: jdbc:postgresql://104.155.176.8:5432/reactivesw
    url: jdbc:postgresql://localhost:5432/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

io:
  reactivesw:
    message:
      brokerType: google
      topic: my-new-topic
      google:
        project:
          id: basic-radius-158809

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000