server:
  port: 8083

spring:
  datasource:
#    url: jdbc:postgresql://104.155.176.8:5432/reactivesw
    url: jdbc:postgresql://localhost:5432/customer_authentication
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

io:
  reactivesw:
    message:
      broker:
        host: http://umasuo.com
      brokerType: google
      google:
        project:
          id: reactivesw-project

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000