server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://pg-data/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: test


jwt:
  secret: QWERTYUIOKJHGFDS
