server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactivesw
#    url: jdbc:postgresql://localhost:5432/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: test


jwt:
  secret: QWERTYUIOKJHGFDS

umasuo:
  test:
    uri: http://localhost:8084/test